---
title: "量的テキスト分析入門"
subtitle: "計量政治学方法論１"
author: "渡辺耕平"
date: "2018年6月28日"
output: 
    ioslides_presentation:
        css: "styles.css"
        widescreen: true
        toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

##量的テキスト分析の流れ

#本講座について

##目標

1. 英語の文書に対する前処理から統計分析までの流れを理解する．
2. 日本語を英語と同様な方法で分析するための特別な前処理を理解する．
3. 政治学的な研究のために英語および日本語の文書を統計的に分析できるようになる．
4. 量的テキスト分析結果を説得に提示できるようになる．


##構成

第1日目

- 講義：量的テキスト分析の歴史および理論的な背景（90分）
- 実習１：Rの基本からコーパスの操作（90分）

第2日目

- 実習２（90分）
- 実習３（90分）

第3日目

- 作業（180分）
- 発表（90分）

##注意点

#量的テキスト分析の 技術的および理論的な背景

##講義の内容

##量的テキスト分析の技術的な背景

量的テキスト分析は自然言語処理の技術を社会・人文科学的な情報を抽出のために応用したものだと考えることができる．

- 自然言語処理技術の応用例
    - 翻訳
    - 検索（Webおよびデータベース）
    - 情報抽出（視覚化やデーターマイニング）
    - 文書要約（ニュース記事）
    - 質疑応答

##自然言語処理の研究の歴史

- 1940s
    - 世界大戦中の暗号解読の経験に基づき自動翻訳の研究が始まった．
- 1950-1960s: 
    - 統計的な手法が開発される一方で，生成文法などの言語理論が登場し，それらに基づくプロトタイプが登場した．
    - アメリカで公的な研究資金の提供が停止するが，政府機関はロシア語の翻訳のために機械翻訳の利用を続けた．
- 1970-1980s
    - 文書が生成された目的や文脈を考慮しながら，より実用性を重視したプログラムのための研究が行われるようになった．
- 1990s
    - コンピューターの性能の向上，電子的データの増加，インターネットの登場によって技術が急速に発展した．
- 2000-2010s:
    - ニューラルネットワークなどの機械学習を用いた手法が急速に発展しつつある．

##量的テキスト分析の発展

- 1950-1960s: メインフレーム上で辞書分析を行うシステムが開発された
    - General Inquirerシステムおよび辞書 (Stone et al. 1966)
        - Hravard III Psychosociological Dictionary
        - Santa Fe Anthropological Dictionary
        - Stanford Political Dictionary  
- 1970-1980s: 複数の量的テキスト分析用の辞書が作成された
    - The Regressive Imagery Dictionary (Martindale 1975)
    - DICTION (North et al. 1984)
- 1990s: 大規模コーパスの統計的な分析手法が開発された
    - Latent Semantic Analysis (Deerwester et al. 1990)
- 2000-2010s: さまざまなテキスト分析に利用できる機械学習モデルが開発された
    - Wordscores (Laver et al. 2003)
    - Latent Dirichlet allocation (Blei 2003)
    - Wordfish (Slapin and Proksch, 2008)

##量的テキスト分析の目的と方法

###目的

社会・人文科学の理論的な観点から興味深いパターンをコーパスの中に発見する

###方法

- 社会・人文科学はより高次の言語現象に注目する
    - 低次（形態素，係り受け，語彙，語の意味）
    - 高次（言説，語用的）
- 高次の言語現象を分析するのための手法は，人が言語を理解する方法とは必ずしも一致しない
    - 複雑な統計的な学習モデルを用いる必要は無い

##内容分析とテキスト分析

量的テキスト分析は，統計的な処理を目的とする内容分析と多くの点で一致するが，人による内容分析の自動化が目的ではない．

- 人間: は少数の文書しか読むことができない，文の深い意味を理解することで，言説を明らかにする．
- 機械: 文の深い意味を理解できないが，多数の文書を系統的に処理することで，言説を明らかにする．

量的テキスト分析の結果は，研究者の実社会について知識に基づいて解釈されない限り、社会・人文科学的な意味をなさない点では，内容分析と同じ．

- コンピューターを用いた内容分析は"automated content analysis"と呼ばれることがあるが，Krippendorffに言わせると"computer-assisted content analysis" に過ぎない．

##文書データの分析目的

- 文書の内容の検証
    - 文書の系統的な分析を通じて，特定の主題に関する記述の傾向を検証する．
        - 社会的少数派に関する新聞記事を分析して報道の公平性を検証する．
- 文書の影響力の検証
    - 文書を社会的な反応を示すデータと併せて分析することで，文書の社会的な影響を推定する．
        - 国際ニュースを外国に関する世論調査のデータと併せて分析することで，メディアの世論形成の力を推定する．
- 文書を代理した測定
    - 文書を通じて直接には測定できない社会現象を測定する．
        - 新聞記事を過去に遡って分析することで，特定の主題に関する世論の歴史的な変化を計測する．
        - ツイートを一定期間継続的に分析することで，特定の主題に関する態度の変化を測定する．
- 文書からの真意の推測    
    - 文書の内容は，その筆者の意識を反映するため，文書データの系統的な分析を通じて，筆者の真の意図を推測する．
        - 政党や政治家の選好を選挙公約や議会議事録を通じて推測する．
        - 国営の外国向けニュースを分析することで，その国の外交戦略の優先課題を推測する．




##量的テキスト分析を用いた研究の流れ

1. 課題を特定
2. コーパス構築（アーカイブやウェブサイトから文書を収集）
3. 前処理
    - 文書単位の変更（必要であれば文書を段落や文節に分割）
    - トークン化（文を語に分割）
    - 特徴選択（重要な語を選択）
4. データ分析
    - 文書データに対する分析（辞書分析やトピックモデルなどを適用）
    - データの集計・統合（必要であれば文書からのデータを加える）
    - 数値データに対する分析（相関分析や回帰分析）
5. 結果の解釈

##量的テキスト分析の種類

###記号的アプローチ

分析者の知識に基づいて事前に作成された辞書などを用いて文書を分析する

- 分析結果が分析者の知識に大いに依存する
- コーパスの大きさに関係なく適用できる
- 技術的に単純で計算量が少ない

###統計的アプローチ

わずかな事前の知識だけで統計モデルを用いて文書を分析する

- 統計モデルの特性に分析結果が依存する
- ある程度大きなコーパスが必要
- 技術的に高度で計算量も多い


##統計的モデルの種類

- generative model
- non-generative model

dimension reduction (dictionary, SVD)



##参考文献

Indurkhya, N., & Damerau, F. J. (2010). Handbook of Natural Language Processing (2nd ed.). Chapman & Hall/CRC.

Liddy, E. D. (2001). Natural language processing. In M. Dekker (Ed.), Encyclopedia of Library and Information Science (2nd edition). Retrieved from http://surface.syr.edu/cgi/viewcontent.cgi?article=1019&context=cnlp

Slocum, J. (1985). A survey of machine translation: its history, current status, and future prospects. Computational Linguistics, 11(1), 1–17.

Krippendorff, K. (2012). Content Analysis: An Introduction to Its Methodology. SAGE.

